/**
 * Builds an SVG sprite + a name union type from the phosphor SVGs fetched into
 * `other/sly/icons` (via `pnpm add-icon`, source: iconify `ph` set).
 *
 * Outputs:
 *   - app/components/icons/sprite.svg  (one <symbol> per icon)
 *   - app/components/icons/name.d.ts   (exported IconName union)
 *
 * Node-only, zero dependencies. Run with `node ./other/build-icons.mjs`.
 */
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const iconsDir = join(here, "sly", "icons");
const outDir = join(here, "..", "app", "components", "icons");

const files = readdirSync(iconsDir)
  .filter((f) => f.endsWith(".svg"))
  .sort();

const symbols = [];
const names = [];
for (const file of files) {
  const name = file.replace(/\.svg$/, "");
  const raw = readFileSync(join(iconsDir, file), "utf8");
  const viewBox = raw.match(/viewBox="([^"]+)"/)?.[1] ?? "0 0 256 256";
  const inner = raw.match(/<svg[^>]*>([\s\S]*?)<\/svg>/)?.[1]?.trim();
  if (!inner) {
    throw new Error(`Could not parse SVG body for ${file}`);
  }
  symbols.push(`<symbol id="${name}" viewBox="${viewBox}">${inner}</symbol>`);
  names.push(name);
}

const sprite = `<svg xmlns="http://www.w3.org/2000/svg">${symbols.join("")}</svg>\n`;
const union = `${names.map((n) => `  | "${n}"`).join("\n")}`;
const dts = `// Generated by other/build-icons.mjs — do not edit by hand.\nexport type IconName =\n${union};\n`;

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "sprite.svg"), sprite);
writeFileSync(join(outDir, "name.d.ts"), dts);

console.log(
  `build-icons: wrote ${names.length} symbols -> app/components/icons/sprite.svg`,
);
